#!/usr/bin/env bash
#
# Snapshot test runner for the AlgoFlow Java engine.
#
# Usage:
#   ./snapshot_test.sh generate   — run all examples, save visualization.json as golden snapshots
#   ./snapshot_test.sh verify     — run all examples, compare against golden snapshots
#   ./snapshot_test.sh run <slug> — run a single example and print its output
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../../../../../" && pwd)"
ENGINE_DIR="$REPO_ROOT/packages/java/engine"
JAR="$ENGINE_DIR/target/algo-transformer-1.0-SNAPSHOT.jar"
EXAMPLES_DIR="$SCRIPT_DIR/examples"
SNAPSHOTS_DIR="$SCRIPT_DIR/snapshots"
RUNNER_PACKAGE="com.algoflow.runner"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m'

if [[ ! -f "$JAR" ]]; then
    echo -e "${YELLOW}Engine JAR not found. Building...${NC}"
    (cd "$ENGINE_DIR" && mvn package -q -DskipTests)
fi

# Normalize visualization.json for stable comparison:
# - Strip random tracer keys (8-char alphanumeric) and replace with positional placeholders
# - This makes snapshots deterministic across runs
normalize_json() {
    python3 - "$1" << 'PYEOF'
import json, sys, re

with open(sys.argv[1]) as f:
    commands = json.load(f)

# Tracer keys are 8-char lowercase alphanumeric strings generated by the library.
# Only remap those — leave human-readable strings like "CallStack" untouched.
KEY_PATTERN = re.compile(r'^[a-z0-9]{8}$')

# First pass: collect all actual tracer keys from the "key" field
raw_keys = set()
for cmd in commands:
    k = cmd.get("key")
    if k and KEY_PATTERN.match(k):
        raw_keys.add(k)

# Assign stable names in order of first appearance
key_map = {}
counter = 0
for cmd in commands:
    k = cmd.get("key")
    if k in raw_keys and k not in key_map:
        key_map[k] = f"tracer_{counter:03d}"
        counter += 1

# Also normalize System.identityHashCode values used as node IDs.
# These appear as large numeric strings (6-10 digits) in args for
# addNode, addEdge, visit, leave, select, deselect, layoutTree, etc.
NODE_ID_METHODS = {'addNode', 'addEdge', 'visit', 'leave', 'select', 'deselect',
                   'layoutTree', 'removeNode', 'removeEdge', 'updateNode', 'objectRef'}
NUMERIC_ID = re.compile(r'^-?\d{6,}$')
node_id_map = {}
node_counter = 0

def stable_node_id(v):
    global node_counter
    if isinstance(v, str) and NUMERIC_ID.match(v):
        if v not in node_id_map:
            node_id_map[v] = f"node_{node_counter:03d}"
            node_counter += 1
        return node_id_map[v]
    return v

# Also normalize identity hash codes that appear as floats (e.g. 1.67560336E9)
# in objectRef args and as the 3rd column in locals/fields set commands.
# Also used for decimal hashes in strings like "Instance: Main@1648217898".
hash_map = {}
hash_counter = 0

def stable_hash(v):
    """Map a raw hash value (float or string of digits) to a stable placeholder."""
    global hash_counter
    key = str(int(v)) if isinstance(v, float) else str(v)
    if key not in hash_map:
        hash_map[key] = f"HASH{hash_counter}"
        hash_counter += 1
    return hash_map[key]

def replace_at_hex_hash(m):
    """Regex replacement for @<hex> hashes in strings."""
    return '@HASH'

def replace_at_hash(m):
    """Regex replacement function for @<decimal> in strings."""
    return '@HASH'

def replace_val(v):
    if isinstance(v, str):
        if v in key_map:
            return key_map[v]
        # Scrub JVM identity hashes: hex (@2b4c3c29) then decimal (@1648217898)
        # Hex pattern requires at least one a-f char to avoid matching pure decimal
        v = re.sub(r'@(?=[0-9a-f]*[a-f])[0-9a-f]{6,8}', replace_at_hex_hash, v)
        v = re.sub(r'@\d{6,10}', replace_at_hash, v)
        return v
    if isinstance(v, float) and v > 1e6:
        return stable_hash(v)
    if isinstance(v, list):
        return [replace_val(item) for item in v]
    return v

def replace_val_with_nodes(v):
    if isinstance(v, str):
        if v in key_map:
            return key_map[v]
        v = re.sub(r'@(?=[0-9a-f]*[a-f])[0-9a-f]{6,8}', replace_at_hex_hash, v)
        v = re.sub(r'@\d{6,10}', replace_at_hash, v)
        return stable_node_id(v)
    if isinstance(v, float) and v > 1e6:
        return stable_hash(v)
    if isinstance(v, list):
        return [replace_val_with_nodes(item) for item in v]
    return v

normalized = []
for cmd in commands:
    method = cmd.get("method", "")
    args = cmd.get("args", [])
    new_args = []
    for a in args:
        if method in NODE_ID_METHODS:
            new_args.append(replace_val_with_nodes(a))
        else:
            new_args.append(replace_val(a))
    normalized.append({
        "key": key_map.get(cmd.get("key"), cmd.get("key")),
        "method": method,
        "args": new_args
    })

print(json.dumps(normalized, indent=2, sort_keys=False))
PYEOF
}

run_example() {
    local slug="$1"
    local java_file="$EXAMPLES_DIR/${slug}.java"
    local tmp_dir
    tmp_dir=$(mktemp -d)

    # Extract class name from the java file
    local class_name
    class_name=$(sed -n 's/.*public[[:space:]]\{1,\}class[[:space:]]\{1,\}\([A-Za-z_][A-Za-z0-9_]*\).*/\1/p' "$java_file" | head -1)

    cp "$java_file" "$tmp_dir/${class_name}.java"

    # Compile
    if ! javac -d . -cp "$JAR" -g "${class_name}.java" 2>"$tmp_dir/compile_err.txt" \
         -C "$tmp_dir" 2>/dev/null; then
        # Try from within tmp_dir
        if ! (cd "$tmp_dir" && javac -d . -cp "$JAR" -g "${class_name}.java" 2>compile_err.txt); then
            echo -e "${RED}COMPILE FAIL${NC}: $slug"
            cat "$tmp_dir/compile_err.txt" >&2
            rm -rf "$tmp_dir"
            return 1
        fi
    fi

    # Run with agent
    local exit_code=0
    (cd "$tmp_dir" && \
     ALGORITHM_VISUALIZER=true java -Xmx512m \
       -javaagent:"$JAR" \
       -cp "$JAR":. \
       --add-opens java.base/java.util=ALL-UNNAMED \
       "${RUNNER_PACKAGE}.${class_name}" >/dev/null 2>/dev/null) || exit_code=$?

    if [[ $exit_code -ne 0 ]]; then
        echo -e "${RED}RUNTIME FAIL${NC}: $slug (exit $exit_code)"
        rm -rf "$tmp_dir"
        return 1
    fi

    if [[ ! -f "$tmp_dir/visualization.json" ]]; then
        echo -e "${RED}NO OUTPUT${NC}: $slug (visualization.json not generated)"
        rm -rf "$tmp_dir"
        return 1
    fi

    # Normalize and output
    normalize_json "$tmp_dir/visualization.json"
    rm -rf "$tmp_dir"
}

cmd_generate() {
    mkdir -p "$SNAPSHOTS_DIR"
    local total=0 pass=0 fail=0

    while IFS= read -r slug; do
        total=$((total + 1))
        echo -n "  Generating: $slug ... "
        if output=$(run_example "$slug" 2>&1); then
            echo "$output" > "$SNAPSHOTS_DIR/${slug}.json"
            echo -e "${GREEN}OK${NC}"
            pass=$((pass + 1))
        else
            echo -e "${RED}FAIL${NC}"
            echo "$output" >&2
            fail=$((fail + 1))
        fi
    done < "$EXAMPLES_DIR/manifest.txt"

    echo ""
    echo -e "Generated: ${GREEN}$pass${NC}/$total passed, ${RED}$fail${NC} failed"
    echo "Snapshots saved to: $SNAPSHOTS_DIR/"
}

cmd_verify() {
    if [[ ! -d "$SNAPSHOTS_DIR" ]]; then
        echo -e "${RED}No snapshots found. Run './snapshot_test.sh generate' first.${NC}"
        exit 1
    fi

    local total=0 pass=0 fail=0 missing=0

    while IFS= read -r slug; do
        total=$((total + 1))
        local snapshot="$SNAPSHOTS_DIR/${slug}.json"

        if [[ ! -f "$snapshot" ]]; then
            echo -e "  ${YELLOW}SKIP${NC}: $slug (no snapshot)"
            missing=$((missing + 1))
            continue
        fi

        echo -n "  Verifying: $slug ... "
        if actual=$(run_example "$slug" 2>&1); then
            if diff <(echo "$actual") "$snapshot" > /dev/null 2>&1; then
                echo -e "${GREEN}PASS${NC}"
                pass=$((pass + 1))
            else
                echo -e "${RED}DIFF${NC}"
                diff <(echo "$actual") "$snapshot" | head -30
                fail=$((fail + 1))
            fi
        else
            echo -e "${RED}FAIL${NC} (execution error)"
            fail=$((fail + 1))
        fi
    done < "$EXAMPLES_DIR/manifest.txt"

    echo ""
    echo -e "Results: ${GREEN}$pass${NC} passed, ${RED}$fail${NC} failed, ${YELLOW}$missing${NC} skipped out of $total"

    if [[ $fail -gt 0 ]]; then
        exit 1
    fi
}

cmd_run() {
    local slug="$1"
    if [[ ! -f "$EXAMPLES_DIR/${slug}.java" ]]; then
        echo "Unknown example: $slug"
        echo "Available: $(cat "$EXAMPLES_DIR/manifest.txt" | tr '\n' ' ')"
        exit 1
    fi
    run_example "$slug"
}

case "${1:-help}" in
    generate)
        echo "=== Generating golden snapshots ==="
        cmd_generate
        ;;
    verify)
        echo "=== Verifying against golden snapshots ==="
        cmd_verify
        ;;
    run)
        if [[ -z "${2:-}" ]]; then
            echo "Usage: $0 run <slug>"
            exit 1
        fi
        cmd_run "$2"
        ;;
    *)
        echo "Usage: $0 {generate|verify|run <slug>}"
        echo ""
        echo "  generate  — Run all examples and save visualization.json as golden snapshots"
        echo "  verify    — Run all examples and compare against golden snapshots"
        echo "  run <slug> — Run a single example"
        exit 1
        ;;
esac
